/**
 * Stillnest schema.
 *
 * Three rules this file exists to enforce, and they are the ones that are
 * expensive to get wrong:
 *
 *  1. **Money is integer cents.** No numeric, no float, ever.
 *  2. **A stay is a calendar range, not an instant.** Every stay boundary is a
 *     `date`, never a timestamp. The range is half-open — `[check_in, check_out)`
 *     — so a guest checking out on the 5th and another checking in on the 5th do
 *     not collide.
 *  3. **Derived values are generated by the database**, not written by the app.
 *     `nights` and `total_cents` cannot drift from their inputs because the app
 *     is never allowed to supply them.
 *
 * Two things Drizzle cannot express live in the migration as raw SQL: the
 * pgvector index, and the EXCLUDE constraint that makes double-booking
 * impossible. See drizzle/0000_*.sql — do not reimplement either in TypeScript.
 */

import { sql } from "drizzle-orm";
import {
  boolean,
  date,
  index,
  integer,
  pgEnum,
  pgTable,
  primaryKey,
  real,
  smallint,
  text,
  timestamp,
  unique,
  uniqueIndex,
  uuid,
  varchar,
  vector,
} from "drizzle-orm/pg-core";

/* ------------------------------------------------------------------ *
 *  Enums — the Solitude Index vocabulary
 * ------------------------------------------------------------------ */

export const biome = pgEnum("biome", [
  "forest",
  "snow",
  "desert",
  "bamboo",
  "coast",
  "highland",
]);

/** "none" is a feature, and it is priced as one. */
export const connectivity = pgEnum("connectivity", ["none", "weak", "full"]);

export const propertyStatus = pgEnum("property_status", ["draft", "live"]);

export const bookingStatus = pgEnum("booking_status", [
  "pending",
  "confirmed",
  "cancelled",
  "expired",
]);

export const blockReason = pgEnum("block_reason", [
  "maintenance",
  "owner",
  "hold",
]);

export const sceneKind = pgEnum("scene_kind", [
  "exterior",
  "interior",
  "view",
  "weather",
]);

export const userRole = pgEnum("user_role", ["guest", "admin"]);

/* ------------------------------------------------------------------ *
 *  Auth.js v5 — the adapter owns the shape of these four tables.
 *  Do not add app columns here; put them on `profiles` instead.
 * ------------------------------------------------------------------ */

export const users = pgTable("users", {
  id: text("id")
    .primaryKey()
    .$defaultFn(() => crypto.randomUUID()),
  name: text("name"),
  email: text("email").notNull().unique(),
  emailVerified: timestamp("email_verified", { withTimezone: true }),
  image: text("image"),
});

export const accounts = pgTable(
  "accounts",
  {
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    type: text("type").notNull(),
    provider: text("provider").notNull(),
    providerAccountId: text("provider_account_id").notNull(),
    refresh_token: text("refresh_token"),
    access_token: text("access_token"),
    expires_at: integer("expires_at"),
    token_type: text("token_type"),
    scope: text("scope"),
    id_token: text("id_token"),
    session_state: text("session_state"),
  },
  (t) => [primaryKey({ columns: [t.provider, t.providerAccountId] })],
);

export const sessions = pgTable("sessions", {
  sessionToken: text("session_token").primaryKey(),
  userId: text("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  expires: timestamp("expires", { withTimezone: true }).notNull(),
});

export const verificationTokens = pgTable(
  "verification_tokens",
  {
    identifier: text("identifier").notNull(),
    token: text("token").notNull(),
    expires: timestamp("expires", { withTimezone: true }).notNull(),
  },
  (t) => [primaryKey({ columns: [t.identifier, t.token] })],
);

/* ------------------------------------------------------------------ *
 *  Profiles — our columns about a user.
 *
 *  `role` is never settable from the app. Admin promotion is a SQL
 *  statement a human runs on purpose.
 * ------------------------------------------------------------------ */

export const profiles = pgTable("profiles", {
  userId: text("user_id")
    .primaryKey()
    .references(() => users.id, { onDelete: "cascade" }),
  fullName: text("full_name"),
  role: userRole("role").notNull().default("guest"),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

/* ------------------------------------------------------------------ *
 *  Properties — and the Solitude Index that replaces bedrooms and price
 *  as the way anyone actually searches.
 * ------------------------------------------------------------------ */

export const properties = pgTable(
  "properties",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    slug: varchar("slug", { length: 80 }).notNull().unique(),
    name: text("name").notNull(),
    tagline: text("tagline"),
    description: text("description").notNull(),

    biome: biome("biome").notNull(),
    country: text("country").notNull(),
    region: text("region").notNull(),
    lat: real("lat").notNull(),
    lng: real("lng").notNull(),

    capacity: smallint("capacity").notNull(),
    bedrooms: smallint("bedrooms").notNull(),

    /** Nightly rate in integer cents. Seasonal overrides live in pricing_rules. */
    basePriceCents: integer("base_price_cents").notNull(),
    minNights: smallint("min_nights").notNull().default(2),

    /* --- the Solitude Index --------------------------------------- */
    /** km to the nearest permanent human dwelling */
    solitudeKm: real("solitude_km").notNull(),
    /** measured ambient level in dB; 32 dB = you hear your own breathing */
    noiseDb: smallint("noise_db").notNull(),
    connectivity: connectivity("connectivity").notNull(),
    /** Bortle dark-sky class, 1 (pristine) to 9 (inner city) */
    bortle: smallint("bortle").notNull(),

    status: propertyStatus("status").notNull().default("draft"),

    /**
     * text-embedding-3-small. Nullable because a property exists before it is
     * embedded; the admin re-embed action fills it. The ivfflat index is added
     * in raw SQL — Drizzle cannot express it.
     */
    embedding: vector("embedding", { dimensions: 1536 }),

    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    index("properties_biome_idx").on(t.biome),
    index("properties_status_idx").on(t.status),
    index("properties_solitude_idx").on(t.solitudeKm),
  ],
);

/* ------------------------------------------------------------------ *
 *  Media
 * ------------------------------------------------------------------ */

export const propertyImages = pgTable(
  "property_images",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    propertyId: uuid("property_id")
      .notNull()
      .references(() => properties.id, { onDelete: "cascade" }),
    /** A media KEY, never a URL. src/lib/media.ts resolves it. */
    path: text("path").notNull(),
    alt: text("alt").notNull(),
    sort: smallint("sort").notNull().default(0),
    isHero: boolean("is_hero").notNull().default(false),
  },
  (t) => [index("property_images_property_idx").on(t.propertyId, t.sort)],
);

/** A living scene: a poster that always renders, and optional loop + sound bed. */
export const propertyScenes = pgTable(
  "property_scenes",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    propertyId: uuid("property_id")
      .notNull()
      .references(() => properties.id, { onDelete: "cascade" }),
    kind: sceneKind("kind").notNull(),
    /** Never optional — it is what shows under prefers-reduced-motion. */
    posterPath: text("poster_path").notNull(),
    videoPath: text("video_path"),
    audioPath: text("audio_path"),
    caption: text("caption"),
    sort: smallint("sort").notNull().default(0),
  },
  (t) => [index("property_scenes_property_idx").on(t.propertyId, t.sort)],
);

/* ------------------------------------------------------------------ *
 *  Amenities
 * ------------------------------------------------------------------ */

export const amenities = pgTable("amenities", {
  id: uuid("id").primaryKey().defaultRandom(),
  slug: varchar("slug", { length: 60 }).notNull().unique(),
  label: text("label").notNull(),
  icon: text("icon"),
});

export const propertyAmenities = pgTable(
  "property_amenities",
  {
    propertyId: uuid("property_id")
      .notNull()
      .references(() => properties.id, { onDelete: "cascade" }),
    amenityId: uuid("amenity_id")
      .notNull()
      .references(() => amenities.id, { onDelete: "cascade" }),
  },
  (t) => [primaryKey({ columns: [t.propertyId, t.amenityId] })],
);

/* ------------------------------------------------------------------ *
 *  Availability and pricing — Python owns the logic, this owns the facts.
 *
 *  Both use half-open ranges: `starts_on` is occupied, `ends_on` is not.
 * ------------------------------------------------------------------ */

export const pricingRules = pgTable(
  "pricing_rules",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    propertyId: uuid("property_id")
      .notNull()
      .references(() => properties.id, { onDelete: "cascade" }),
    startsOn: date("starts_on").notNull(),
    endsOn: date("ends_on").notNull(),
    priceCents: integer("price_cents").notNull(),
    /** Overrides the property's minimum for this window when present. */
    minNights: smallint("min_nights"),
    label: text("label"),
  },
  (t) => [index("pricing_rules_property_idx").on(t.propertyId, t.startsOn)],
);

export const availabilityBlocks = pgTable(
  "availability_blocks",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    propertyId: uuid("property_id")
      .notNull()
      .references(() => properties.id, { onDelete: "cascade" }),
    startsOn: date("starts_on").notNull(),
    endsOn: date("ends_on").notNull(),
    reason: blockReason("reason").notNull(),
    note: text("note"),
  },
  (t) => [index("availability_blocks_property_idx").on(t.propertyId, t.startsOn)],
);

/* ------------------------------------------------------------------ *
 *  Bookings
 *
 *  `nights` and `total_cents` are GENERATED — the app cannot supply them,
 *  so they cannot disagree with the columns they are derived from.
 *
 *  Overlap prevention is an EXCLUDE constraint added in raw SQL. It is the
 *  real guarantee; application checks are only there to give a nice error
 *  before the database gives a blunt one.
 * ------------------------------------------------------------------ */

export const bookings = pgTable(
  "bookings",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    propertyId: uuid("property_id")
      .notNull()
      .references(() => properties.id, { onDelete: "restrict" }),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "restrict" }),

    checkIn: date("check_in").notNull(),
    checkOut: date("check_out").notNull(),
    guests: smallint("guests").notNull(),

    nights: integer("nights").generatedAlwaysAs(
      (): ReturnType<typeof sql> => sql`(${bookings.checkOut} - ${bookings.checkIn})`,
    ),

    subtotalCents: integer("subtotal_cents").notNull(),
    feesCents: integer("fees_cents").notNull().default(0),
    totalCents: integer("total_cents").generatedAlwaysAs(
      (): ReturnType<typeof sql> =>
        sql`(${bookings.subtotalCents} + ${bookings.feesCents})`,
    ),

    status: bookingStatus("status").notNull().default("pending"),

    /** Unique so a replayed Stripe webhook cannot create a second booking. */
    stripeSessionId: text("stripe_session_id"),
    /** A pending hold releases itself if checkout is abandoned. */
    expiresAt: timestamp("expires_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    uniqueIndex("bookings_stripe_session_idx").on(t.stripeSessionId),
    index("bookings_property_idx").on(t.propertyId, t.checkIn),
    index("bookings_user_idx").on(t.userId, t.checkIn),
  ],
);

/* ------------------------------------------------------------------ */

export const savedStays = pgTable(
  "saved_stays",
  {
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    propertyId: uuid("property_id")
      .notNull()
      .references(() => properties.id, { onDelete: "cascade" }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    primaryKey({ columns: [t.userId, t.propertyId] }),
    unique("saved_stays_unique").on(t.userId, t.propertyId),
  ],
);
